version: '3'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'socks-store-postgres'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=store'