version: '3'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'socks-store-postgres'
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=store'

  app:
    build: ./
    container_name: 'socks-store-app'
    ports:
      - 8080:8080